import type { Icon as LucidIcon } from "lucide-react";
import {
	ArrowUpRight,
	Camera,
	Check,
	ChevronDown,
	ChevronRight,
	ChevronUp,
	Circle,
	Cloud,
	// Github,
	Heart,
	Home,
	LayoutGrid,
	List,
	Loader2,
	LogOut,
	MapPin,
	MoreHorizontal,
	Pencil,
	Save,
	Search,
	Settings,
	Share,
	TimerIcon,
	Trash,
	Upload,
	User,
	X,
} from "lucide-react";
import { BiPhotoAlbum } from "react-icons/bi";

export type Icon = typeof LucidIcon;

export const Icons = {
	home: Home,
	photos: BiPhotoAlbum,
	settings: Settings,
	arrowUpRight: ArrowUpRight,
	upload: Upload,
	cloud: Cloud,
	// github: Github,
	logout: LogOut,
	user: User,
	heart: Heart,
	mapPin: MapPin,
	moreHorizontal: MoreHorizontal,
	pencil: Pencil,
	loader: Loader2,
	search: Search,
	layoutGrid: LayoutGrid,
	list: List,
	save: Save,
	trash: Trash,
	time: TimerIcon,
	x: X,
	check: Check,
	chevronDown: ChevronDown,
	chevronUp: ChevronUp,
	circle: Circle,
	chevronRight: ChevronRight,
	share: Share,
	close: X,
	camera: Camera,
};
